### ISSUE TITLE
build --production fails on broccoli

### ISSUE THREAD

**Issue by AshMartian** [isleofcode/ember-cordova#1]
When trying to build with the --production flag, my project fails with this error. Unsure where to start looking for resolutions.

`ember cdv:build --platform=android --environment=production`
```
EmberCordovaError: The Broccoli Plugin: [Fingerprint] failed with:
    at new BroccoliBuildError (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-builder/lib/broccoli-build-error.js:40:9)
    at /Users/brandon/Documents/HappyLeaf/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/brandon/Documents/HappyLeaf/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/brandon/Documents/HappyLeaf/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/brandon/Documents/HappyLeaf/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/Users/brandon/Documents/HappyLeaf/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/Users/brandon/Documents/HappyLeaf/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Fingerprint.Plugin (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-asset-rev/lib/fingerprint.js:27:10)
    at Fingerprint (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-asset-rev/lib/fingerprint.js:22:12)
    at new AssetRev (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-asset-rev/lib/asset-rev.js:27:25)
    at AssetRev (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/brandon/Documents/HappyLeaf/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/brandon/Documents/HappyLeaf/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/brandon/Documents/HappyLeaf/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)


```

**Comment by jfrux** [comment]
I'm getting this error too... anyone have any updates on this?

**Comment by alexblom** [comment]
@joshuairl @blandman I'm unable to replicate. Can somebody hop on a screenhero so I can see? 

Can you also confirm you are on the latest ember-cordova version, and also share your ember version?

**Comment by alexblom** [comment]
Closing as I can't replicate. Please re-open if still present.
