### ISSUE TITLE
Problem installing: "App id contains reserved word"

### ISSUE THREAD

**Issue by ksnyde** [isleofcode/ember-cordova#17]
I have a small spike I'd got working with `ember-cli-cordova` and wanted to switch over to `ember-cordova`. I did the following:

- removed `ember-cli-cordova` from my package.json
- ran `ember install ember-cordova`, this resulted in the following error:

![2016-03-27_12-49-24](https://cloud.githubusercontent.com/assets/980757/14065258/7c408a5e-f41a-11e5-9309-6111cfcf0ab8.png)

Error seems to originate from the `ember-cordova/lib/tasks/bash.js` shell script, stack trace is:

> Error: Command failed: cordova create cordova mobile-spike mobile-spike
    at checkExecSyncError (child_process.js:469:13)
    at execSync (child_process.js:509:13)
    at /Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cordova/lib/tasks/bash.js:23:7
    at lib$rsvp$$internal$$initializePromise (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.run (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cordova/lib/tasks/bash.js:17:12)
    at Class.module.exports.Task.extend.run (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cordova/lib/tasks/create-cordova-project.js:30:21)
    at Class.module.exports.afterInstall (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cordova/blueprints/ember-cordova/index.js:34:19)
    at lib$rsvp$$internal$$tryCatch (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)

**Comment by ksnyde** [comment]
Ok, it appears that the problem is Cordova doesn't like the dash in my project's name but I think project names with dashes are too common not to see this as something that the plugin handles. Agree?

**Comment by AlexBlom** [comment]
I agree that this should be handled on our side. Will make sure I fix tomorrow.
