### ISSUE TITLE
problem with cdv:build --environment=production

### ISSUE THREAD

**Issue by peillis** [isleofcode/ember-cordova#183]
Strangely this doesn't happen in dev environment.

ember cdv:build -prod
```
Building
File: plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4.js
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENAMETOOLONG: name too long, open '/Users/enrique/webs/comiditas/tmp/fingerprint-output_path-sVn37Akt.tmp/plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at FSMonitor._measure (/Users/enrique/webs/comiditas/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.openSync (/Users/enrique/webs/comiditas/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at FSMonitor._measure (/Users/enrique/webs/comiditas/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.writeFileSync (/Users/enrique/webs/comiditas/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at /Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/lib/fingerprint.js:79:8
    at tryCatch (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/node_modules/rsvp/dist/rsvp.js:553:13)

The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/node_modules/broccoli-filter/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/lib/fingerprint.js:27:10)
    at Fingerprint (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/lib/fingerprint.js:22:12)
    at new AssetRev (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/lib/asset-rev.js:27:25)
    at AssetRev (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.module.exports.postprocessTree (/Users/enrique/webs/comiditas/node_modules/broccoli-asset-rev/index.js:31:40)
    at /Users/enrique/webs/comiditas/node_modules/ember-cli/lib/broccoli/ember-app.js:543:27
    at Array.forEach (native)
    at EmberApp.addonPostprocessTree (/Users/enrique/webs/comiditas/node_modules/ember-cli/lib/broccoli/ember-app.js:541:23)
```

**Comment by tavosansal** [comment]
I had this same issue. Fingerprinting was the culprit since some of the files become gigantic and broccoli cannot access them. I ended up disabling fingerprinting for ember-cli on production (https://ember-cli.com/asset-compilation#fingerprinting-and-cdn-urls)

**Comment by peillis** [comment]
You're right, disabling fingerprinting works. But looks like an error of cdv:build because the command: `ember build --environment=production` works fine.
It seems that the hash for some reason it's applied multiple times:
`ios-wkwebview-exec-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4-dd057aadedf036cf82fed076b6f81eb4.js`

**Comment by peillis** [comment]
Maybe this is the same problem as #164 ?

**Comment by utilityboy** [comment]
Yes.  See here for a workaround: 

https://github.com/isleofcode/ember-cordova/issues/181#issuecomment-255542216
