### ISSUE TITLE
SyntaxError in platform.js

### ISSUE THREAD

**Issue by ksnyde** [isleofcode/ember-cordova#19]
Trying to serve my app after conversion from `ember-cli-cordova` to `ember-cordova` (also changed name to 'mobile.spike' to avoid the dash-constraint raised as separate issue).

SyntaxError: modules/ember-cordova/services/device/platform.js: Line 160: "v" is read-only

        const v = version.toString();
        if (v.indexOf('.') > 0) {
          v = v.replace('.', '_');
        } else {
          v += '_0';
        }

>    at File.errorWithNode (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/file/index.js:489:13)
    at NodePath.errorWithNode (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/path/index.js:155:26)

    at NodePath.Scope (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/transformers/es6/constants.js:48:25)
    at NodePath.<anonymous> (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/visitors.js:221:17)
    at NodePath.call (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Volumes/PEGASUS/repos/mine/lg2/mobile-spike/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/traversal/path/context.js:107:26)

**Comment by AlexBlom** [comment]
Thanks for the report. Fixed.
