### ISSUE TITLE
A new install of ember-cordova fails to do cdv:build without deleting cordova/www

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/ember-cordova#204]
`ember install ember-cordova` creates `ember-cordova/cordova/www` default cordovacontent. Then when `cdv:build` runs it fails with:

> ENOTEMPTY: directory not empty, rmdir '/Users/kitsunde/Development/test-create-ember-cordova/ember-cordova/cordova/www/js/'

<details>

```
Error: ENOTEMPTY: directory not empty, rmdir '/Users/kitsunde/Development/test-create-ember-cordova/ember-cordova/cordova/www/js/'
    at Object.fs.rmdirSync (fs.js:818:18)
    at FSMonitor._measure (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.rmdirSync (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cli/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at TreeSync.<anonymous> (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/ember-cli/node_modules/tree-sync/index.js:80:19)
    at Array.forEach (native)
    at TreeSync.sync (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/ember-cli/node_modules/tree-sync/index.js:50:14)
    at Class.copyToOutputPath (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/ember-cli/lib/models/builder.js:173:10)
    at /Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/ember-cli/lib/models/builder.js:187:21
    at tryCatch (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/kitsunde/Development/test-create-ember-cordova/node_modules/ember-cordova/node_modules/rsvp/dist/rsvp.js:553:13)
```

</details>

asciinema: https://asciinema.org/a/c9obz11bbg80ugi5pspmb1fn1?t=3:57

Deleting the directory allows ember-cordova to build normally again.

**Comment by alexblom** [comment]
Fixed in 0.3.12.
