### ISSUE TITLE
Index.html not found

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#215]
```
ember-cli: 2.10.0
node: 6.9.2
os: darwin x64
Android Studio: 2.2.3
ember-cordova: 0.3.13
ember-cordova-events": 0.1.0
```

Commands
```
ember install ember-cordova --name=tmob --cordovaid=com.xxxxx.tmob
ember install ember-cordova-events
ember cdv:platform add android
ember cdv build
ember cdv run
```

From Android Studio

```
D/CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/index.html
D/SystemWebViewClient: CordovaWebViewClient.onReceivedError: Error code=-1 Description=net::ERR_FILE_NOT_FOUND URL=file:///android_asset/www/index.html
D/SystemWebChromeClient: data:text/html,chromewebdata: Line 12 : Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png
I/chromium: [INFO:CONSOLE(12)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (12)
D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
```
From Command prompt
```
Error: Failed to install apk to emulator: [  3%] /data/local/tmp/android-debug.apk
[  7%] /data/local/tmp/android-debug.apk
[ 10%] /data/local/tmp/android-debug.apk
[ 14%] /data/local/tmp/android-debug.apk
[ 18%] /data/local/tmp/android-debug.apk
[ 21%] /data/local/tmp/android-debug.apk
[ 25%] /data/local/tmp/android-debug.apk
[ 28%] /data/local/tmp/android-debug.apk
[ 32%] /data/local/tmp/android-debug.apk
[ 36%] /data/local/tmp/android-debug.apk
[ 39%] /data/local/tmp/android-debug.apk
[ 43%] /data/local/tmp/android-debug.apk
[ 47%] /data/local/tmp/android-debug.apk
[ 50%] /data/local/tmp/android-debug.apk
[ 54%] /data/local/tmp/android-debug.apk
[ 57%] /data/local/tmp/android-debug.apk
[ 61%] /data/local/tmp/android-debug.apk
[ 65%] /data/local/tmp/android-debug.apk
[ 68%] /data/local/tmp/android-debug.apk
[ 72%] /data/local/tmp/android-debug.apk
[ 76%] /data/local/tmp/android-debug.apk
[ 79%] /data/local/tmp/android-debug.apk
[ 83%] /data/local/tmp/android-debug.apk
[ 86%] /data/local/tmp/android-debug.apk
[ 90%] /data/local/tmp/android-debug.apk
[ 94%] /data/local/tmp/android-debug.apk
[ 97%] /data/local/tmp/android-debug.apk
[100%] /data/local/tmp/android-debug.apk
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
	pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
You're trying to install apk with a lower versionCode that is already installed.
Either uninstall an app or increment the versionCode.
ERROR: ember-cordova 
Error: Command failed: cordova run
Error: ERROR: ember-cordova 
Error: Command failed: cordova run
    at Object.error (/Users/xxxxxx/projects/tmp/tmob/node_modules/ember-cordova/lib/utils/logger.js:21:11)
    at /Users/xxxxxx/projects/tmp/tmob/node_modules/ember-cordova/lib/commands/cordova.js:75:14
    at tryCatch (/Users/xxxxxx/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/xxxxxx/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/xxxxxx/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:521:7)
    at publishRejection (/Users/xxxxxx/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:456:3)
    at flush (/Users/xxxxxx/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by alexblom** [comment]
Thanks.

This looks related to #212, and I really appreciate the ENV info. Have been struggling to replicate, I'm now going to follow your steps :)

**Comment by alexblom** [comment]
Just took a deeper look at your list. Are you running `ember cdv build` or `ember cdv:build --platform=android`

The space implies a proxy command, and will only run cordova build. `ember cdv:build` is our command which first runs an ember-build, ensuring you have an index.html file.

**Comment by hashg** [comment]
I run `ember cdv build`

**Comment by alexblom** [comment]
Ok, I think you are looking for `ember cdv:build` in the context you have provided. In general, proxy commands are for advanced usage when you want to deliberately change a Cordova-something.

**Comment by hashg** [comment]
`ember cdv:build --platform=android` fixed the issue.
