### ISSUE TITLE
Ember cdv:build error

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#218]
1. Install `Ember Cordova`
2. Add `iOS` platform
3. Add `Android` platform
4. `ember cdv:build`
5. Remove `iOS` platform
6. `ember cdv:build`

ERROR
```
rmac:tmob hgowda$ ember cdv:build
ember-cordova: Building app
ERROR: ember-cordova 
undefined
Error: ERROR: ember-cordova 
undefined
    at Object.error (/Users/hgowda/projects/tmp/tmob/node_modules/ember-cordova/lib/utils/logger.js:21:11)
    at /Users/hgowda/projects/tmp/tmob/node_modules/ember-cordova/lib/commands/build.js:111:16
    at tryCatch (/Users/hgowda/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/hgowda/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/hgowda/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:521:7)
    at publishRejection (/Users/hgowda/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:456:3)
    at flush (/Users/hgowda/projects/tmp/tmob/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by doppelreim** [comment]
I assume `ember cdv:build` defaults the platform to `ios` (see http://embercordova.com/pages/cli#build). You removed that platform, hence something explodes.

You can explicitely set the platform like so: `ember cdv:build --platform=android`.

Nevertheless, the error-message is not very helpful.

**Comment by hashg** [comment]
Why is iOS treated as first citizen?

**Comment by doppelreim** [comment]
I don't know.

Tried to find out, how to get a clearer error-message, but got lost in the promise-rejection and error-logging logic.

In `./node_modules/ember-cordova/lib/utils/cordova-validator.js` the check inside `validateCordovaJSON` fails, because ios is not present in your configuration.

A somewhat clearer error-message is constructed in `throwError`, but somehow somewhere it gets swallowed and doesn't end up in the console.

**Comment by alexblom** [comment]
ios is the documented default - we don't yet have the capability to see what platform you have installed (if it is only one) and default to it, and it's not really a priority. You can modify your .ember-cli file to override defaults as documented here: http://embercordova.com/pages/cli

We're aware of some errors needing fixing (getting closer), but doppelreim is correct in stating your issue is a result of triggering an iOS build without the platform.
