### ISSUE TITLE
0.4.1: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by reidab** [isleofcode/ember-cordova#235]
After upgrading to 0.4.1 last night, I started getting `TypeError: Cannot read property '0' of undefined` exceptions when running any build command including `ember cdv:build --help`. It seems to be related to https://github.com/heimdalljs/heimdall-fs-monitor/pull/7#discussion_r88314418 and setting up duplicate FS monitors.

I did a quick `git bisect` and it seems like the problem cropped up with the dependency updates in 08017270fdbdf213066e45903f7c7a561fc8d7c6. I'll keep looking into it and see what I can track down.

Full backtrace:
````
TypeError: Cannot read property '0' of undefined
    at Metric.stop (/Users/reidab/code/thedyrt/ui/node_modules/heimdalljs-fs-monitor/index.js:43:40)
    at FSMonitor._measure (/Users/reidab/code/thedyrt/ui/node_modules/heimdalljs-fs-monitor/index.js:68:7)
    at Object.realpathSync (/Users/reidab/code/thedyrt/ui/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at toRealPath (module.js:132:13)
    at tryFile (module.js:128:22)
    at tryPackage (module.js:106:10)
    at Function.Module._findPath (module.js:185:20)
    at Function.Module._resolveFilename (module.js:470:25)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cordova/node_modules/ember-cli/lib/models/builder.js:17:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cordova/lib/tasks/ember-build.js:1:85)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cordova/lib/commands/build.js:7:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cordova/lib/commands/index.js:4:39)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cordova/index.js:3:29)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Function.Addon.lookup (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/models/addon.js:998:19)
    at /Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/models/addons-factory.js:48:38
    at visit (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/utilities/DAG.js:137:7)
    at Class.initializeAddons (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/models/addons-factory.js:44:11)
    at Project.initializeAddons (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/models/project.js:381:36)
    at Project.eachAddonCommand (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/models/project.js:433:10)
    at module.exports (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/reidab/code/thedyrt/ui/node_modules/ember-cli/lib/cli/cli.js:79:26)
    at tryCatch (/Users/reidab/code/thedyrt/ui/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/reidab/code/thedyrt/ui/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/reidab/code/thedyrt/ui/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/reidab/code/thedyrt/ui/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
````

**Comment by alexblom** [comment]
Thanks for this. Completely nuking my example projects to see if I can replicate as well.

**Comment by reidab** [comment]
Tracked it down a bit further to the ember-cli upgrade in that commit.

It looks like this is happening because we're trying to require ember-cli modules from ember-cordova's dependencies after it's already been loaded by ember-cli itself. Looking at the ember-cli addon blueprint, I think moving ember-cli from `dependencies` to `devDependencies` should fix it.

**Comment by reidab** [comment]
This may only be replicable in cases where the global ember-cli version has a mismatch with the `2.9.1` specified in `package.json` — I'm running `2.10.0`.

I've confirmed that moving `ember-cli` out of `dependencies` solves this for me without any noticeable issues. It seems like this is the canonical [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) use case.

I'll toss up a PR moving around the ember-cli dependency and loosening up the version lock to `^2.7.0`, based on the pre-upgrade version.

**Comment by basz** [comment]
I encounter this when doing in a new directory.

```
ember init
ember install ember-cordova
```

```
rattletrap:~ bas$ ember -v
ember-cli: 2.10.0
node: 4.7.2
os: darwin x64
```

**Comment by joshuairl** [comment]
I'm getting this still...
`ember-cordova` version 0.4.5
`ember-cli` version 2.10.0

Any tips?

**Comment by Cryrivers** [comment]
per my experience, you might set `rootURL` or `baseURL` to `null`. Just setting them to `''` would solve this issue.

**Comment by joshuairl** [comment]
Thanks! I'll give it a try and see what happens.
Although this may seem obvious, is there a recommended place to make this variable change?

I don't think I've ever changed that in Ember before?

**Comment by alexblom** [comment]
This is a setting in your config/environment.js. Please do let me know if this resolves the issue for you.

**Comment by joshuairl** [comment]
Setting rootURL to '' fixed the issue.

Thank you!

**Comment by alexblom** [comment]
Can I ask what your rootURL was set to prior? I'd like to update the test case.

**Comment by joshuairl** [comment]
It was set to null by default when ember cli created it. :-/

Thanks!
