### ISSUE TITLE
Support for ember-cli 1.13

### ISSUE THREAD

**Issue by jraoatlogic** [isleofcode/ember-cordova#242]
Does this tool support ember-cli 1.13? It seems the document says it does, but when I try to install it, I got an error.

`ember -v` returns:
```
version: 1.13.8
node: 4.4.4
npm: 2.13.4
os: win32 x64
```

Create app using `ember new hello`, then in hello, execute `ember install ember-cordova` gives the following error:
```
Error: The package ember-cli@1.13.8 does not satisfy its siblings' peerDependencies requirements!
    at E:\hello\node_modules\ember-cli\node_modules\npm\lib\install.js:125:32
    at E:\hello\node_modules\ember-cli\node_modules\npm\lib\install.js:268:7
    at E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
    at E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    at cb (E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    at E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    at cb (E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    at E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    at cb (E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    at E:\hello\node_modules\ember-cli\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
```

**Comment by alexblom** [comment]
Thanks for bringing this up. Unfortunately you will need to stick on version 0.3.15 for now.

Will leave this open and work to get back dow to 1.13 support.

**Comment by alexblom** [comment]
Just updated the test suite with explicit testing for Ember 1.13 and we're passing.

There is a general assumption ember-cli is kept up to date. The prior peerDependencies has been removed as of the latest release, so the issue here could well have resolved itself.
