### ISSUE TITLE
Icon generation fails

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#254]
```
ember-cordova: generating-icons
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

**Comment by alexblom** [comment]
Icon generation requires Node 5+. Can you confirm what version you are running?

**Comment by v3ss0n** [comment]
node 6.2.1

**Comment by alexblom** [comment]
Should be resolved in the latest release, but please re-open if that persists.

**Comment by v3ss0n** [comment]
Thanks i willt est!
