### ISSUE TITLE
Ember cdv:serve failing

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#37]
```
ember-cordova: 0.1.4
ember-cli: 2.5.0
node: 5.3.0
os: darwin x64
```

`$ ember cdv:serve`

`⠋ Buildingember-cordova: /Projects/js/cdv6/cdv/ember-cordova/cordova/platforms/ios/www/cordova_plugins.js did not exist. It is required for Device LiveReload to work.`

Symlinked dist/ to cordova/wwww

`ember-cordova: /Projects/js/cdv6/cdv/ember-cordova/cordova/platforms/ios/www/cordova_plugins.js did not exist. It is required for Device LiveReload to work.`

File: /bin/sh

`Command failed: EMBER_CORDOVA=true CORDOVA_RELOAD_ADDRESS=http://localhost:4200 CORDOVA_PLATFORM=ios  EMBER_CORDOVA=true ember build --environment development`

`Error: Command failed: EMBER_CORDOVA=true CORDOVA_RELOAD_ADDRESS=http://localhost:4200 CORDOVA_PLATFORM=ios  EMBER_CORDOVA=true ember build --environment development`
```
    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at /Projects/js/cdv6/cdv/node_modules/ember-cordova/lib/tasks/bash.js:23:7
    at lib$rsvp$$internal$$initializePromise (/Projects/js/cdv6/cdv/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/Projects/js/cdv6/cdv/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/Projects/js/cdv6/cdv/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.run (/Projects/js/cdv6/cdv/node_modules/ember-cordova/lib/tasks/bash.js:17:12)
    at Class.module.exports.Task.extend.run (/Projects/js/cdv6/cdv/node_modules/ember-cordova/lib/tasks/build.js:44:23)
    at Class.module.exports.run (/Projects/js/cdv6/cdv/node_modules/ember-cordova/lib/commands/serve.js:58:18)
    at Class.<anonymous> (/Projects/js/cdv6/cdv/node_modules/ember-cli/lib/models/command.js:152:17)
```

**Comment by gilest** [comment]
Have you tried removing and re-adding the ios platform?

For example:
`$ ember cdv platform remove ios`
`$ ember cdv platform add ios`

Which version of the ios platform are you using?

You can list your platforms and versions with:
`$ ember cdv platform`

If you aren't using the latest version of the ios platform (`4.1.1`) then I'd suggest trying that. Likewise with the latest version of Cordova (`6.1.1`).

**Comment by hashg** [comment]
Thx. I had older version of Cordova which was pulling ios platform (3.6.x).
