### ISSUE TITLE
Error on 100% clean install

### ISSUE THREAD

**Issue by devinrhode2** [isleofcode/ember-cordova#47]
On a fresh ember app, just after doing `ember new my-app` I install ember-cordova and am getting this error:
```
➤ ember install ember-cordova                          git:master
Installed packages for tooling via npm.
installing ember-cordova
  create /ember-cordova/.npmignore
/bin/sh: cordova: command not found
File: /bin/sh
Command failed: cordova create cordova sympstruments sympstruments
Error: Command failed: cordova create cordova sympstruments sympstruments
    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at /Users/devinrhode2/repos/sympstruments/node_modules/ember-cordova/lib/tasks/bash.js:23:7
    at lib$rsvp$$internal$$initializePromise (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.run (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cordova/lib/tasks/bash.js:17:12)
    at Class.module.exports.Task.extend.run (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cordova/lib/tasks/create-cordova-project.js:30:21)
    at Class.module.exports.afterInstall (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cordova/blueprints/ember-cordova/index.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/devinrhode2/repos/sympstruments/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
sympstruments ➤
```

**Comment by devinrhode2** [comment]
hold the phone.. digging in some more.. may be deleted in 24hr if I don't update any further

**Comment by devinrhode2** [comment]
just had to `npm install -g cordova`
