### ISSUE TITLE
Install fails for Cordova 6.2.0

### ISSUE THREAD

**Issue by hashg** [isleofcode/ember-cordova#49]
- ember new `isleofcode`
- cd `isleofcode/`
- ember `install ember-cordova`

```
Error: Cannot find module 'config-chain'
File: /bin/sh
Command failed: cordova create cordova isleofcode isleofcode
Error: Command failed: cordova create cordova isleofcode isleofcode
    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at /Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cordova/lib/tasks/bash.js:23:7
    at lib$rsvp$$internal$$initializePromise (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.run (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cordova/lib/tasks/bash.js:17:12)
    at Class.module.exports.Task.extend.run (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cordova/lib/tasks/create-cordova-project.js:30:21)
    at Class.module.exports.afterInstall (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cordova/blueprints/ember-cordova/index.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/<user>/Projects/tmp/isleofcode/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
```

**Comment by AlexBlom** [comment]
Silly question: do you have cordova installed already? (e.g. does a cordova create foo command work?)

**Comment by hashg** [comment]
I uninstalled cordova and re-installed it worked.
