### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Dragsbaek** [isleofcode/ember-cordova#57]
getting: 

```
Unexpected token )
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/projects/NuukTaxiApp/nuuk-mobile/node_modules/ember-cordova/lib/tasks/ember-build.js:5:23)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)

```
when running: ember install ember-cordova

**Comment by AlexBlom** [comment]
I'll need to try this on a fresh machine, not an issue I am having. Can you confirm the version you are installing is the latest, and that you are not passing any other params to the ember install?

**Comment by Dragsbaek** [comment]
No extra params.

"ember-cordova": "0.1.7"

cordova: 6.2.0

Thanks

**Comment by AlexBlom** [comment]
Really weird - are you on the ember slack at all? I'm @alexblom there, and may be easier if I can see this really fast on hero. 

I'd also quickly confirm that normal ember builds are working for you - the task that is failing just wraps cordova build, link-env & ember-build.

**Comment by Dragsbaek** [comment]
Found out it was actually npm giving me troubles.. had to downgrade to 3.9.6 and now everything works:D
