### ISSUE TITLE
Don't understand this build failure

### ISSUE THREAD

**Issue by ignotus0001** [isleofcode/ember-cordova#69]
When I try a cordova build with `ember cdv:build --platform=android`, the build fails with

`Error: ember-cordova: You must specify the locationType as 'hash' in your environment.js.
    at Class.module.exports.validateLocationType (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cordova/lib/commands/build.js:66:13)
    at Class.module.exports.run (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cordova/lib/commands/build.js:28:10)
    at Class.<anonymous> (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/billy/BitBucket/Personal/wheres-my-ride/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

I do have `locationType: 'hash',` in my environment.js file, and I also tried using defaultLocationType as is done in ember-cli-cordova. No love. It seems locationType in the validateLocationType() function comes back as undefined.

I fear this is a dumb newbie question, so apologies in advance, but ... what am I missing?

thx.

-Billy B
`

**Comment by alexblom** [comment]
Sorry - it looks like I accepted a faulty merge with some false positive tests. Have rectified - upgrade ember-cordova and you should be good.

**Comment by ignotus0001** [comment]
Yes indeed, all is well. Thanks for the swift turnaround, mon ami.
