### ISSUE TITLE
ember install ember-cordova fails

### ISSUE THREAD

**Issue by utilityboy** [isleofcode/ember-cordova#84]
On a new Ember 2.6 projects, installation of the addon fails with the following:

```
❯ ember install ember-cordova                                                           [13:30:01]
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠧ Installing packages for tooling via npmConsidering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Linking to global install at /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs
Writing location.js file
Installed packages for tooling via npm.
/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:16
   return new Promise(() => {
                       ^
Unexpected token )
/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:16
   return new Promise(() => {
                       ^
SyntaxError: Unexpected token )
   at exports.runInThisContext (vm.js:73:16)
   at Module._compile (module.js:443:25)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (/projects/embercordova/node_modules/ember-cordova/lib/tasks/ember-build.js:4:23)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
>>>elapsed time 35s
```

**Comment by utilityboy** [comment]
Looks like this has to do with running node 0.12.x

**Comment by alexblom** [comment]
Thanks

**Comment by alexblom** [comment]
Closing in favour of #92
