### ISSUE TITLE
Error installing iOS platform

### ISSUE THREAD

**Issue by utilityboy** [isleofcode/ember-cordova#85]
Hi.  Encountering this issue when installing iOS on a newly inited Ember 2.6 repo.

```
ember cdv platform add ios
Running 'cordova platform add ios'
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: cordova
	Name: cordova
iOS project created with cordova-ios@4.2.0
Error: ENOENT: no such file or directory, open '/projects/embercordova/ember-cordova/cordova/platforms/ios/cordova/cordova-Info.plist'
File: /bin/sh
Command failed: cordova platform add ios
Error: Command failed: cordova platform add ios
    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at CoreObject.BashTask.runCommand (/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:28:16)
    at /projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:22:12
    at lib$rsvp$$internal$$initializePromise (/projects/embercordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1084:9)
    at PromiseExt.lib$rsvp$promise$$Promise (/projects/embercordova/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:546:53)
    at new PromiseExt (/projects/embercordova/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at CoreObject.Task.extend.run (/projects/embercordova/node_modules/ember-cordova/lib/tasks/bash.js:16:12)
    at CoreObject.module.exports.run (/projects/embercordova/node_modules/ember-cordova/lib/commands/cordova.js:60:8)
    at CoreObject.module.exports.validateAndRun (/projects/embercordova/node_modules/ember-cordova/lib/commands/cordova.js:45:17)
```

**Comment by alexblom** [comment]
Was ember-cordova installed correctly for you, given #84?

Easy way to tell is if ember-cordova directory exists, etc?

**Comment by utilityboy** [comment]
@alexblom I'm running node v4.2.1, so addon installation succeeded.  I encountered the package installation errors following that.

**Comment by alexblom** [comment]
Thanks, given it is related, I'm going to close this and leave #84 open as our reference issue.

**Comment by utilityboy** [comment]
@alexblom I don't believe this is related.  Running node 4.2.1 this still fails.
