### ISSUE TITLE
Error installing browser platform

### ISSUE THREAD

**Issue by utilityboy** [isleofcode/ember-cordova#87]
Hi. Encountering this issue when installing `browser` on a newly inited Ember 2.6 repo.

```
ember cdv platform add browser
Running 'cordova platform add browser'
Adding browser project...
Running command: /Users/brent/.cordova/lib/npm_cache/cordova-browser/4.1.0/package/bin/create /projects/embercordova/ember-cordova/cordova/platforms/browser cordova cordova
Creating Browser project. Path: platforms/browser
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for browser
Installing "cordova-plugin-whitelist" for ios
Failed to install 'cordova-plugin-whitelist':CordovaError: Could not find *-Info.plist file, or config.xml file.
    at Object.parseProjectFile [as parse] (/projects/embercordova/ember-cordova/cordova/platforms/ios/cordova/lib/projectFile.js:51:15)
    at Api.addPlugin (/projects/embercordova/ember-cordova/cordova/platforms/ios/cordova/Api.js:209:33)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
Failed to restore plugin "cordova-plugin-whitelist" from config.xml. You might need to try adding it again. Error: Could not find *-Info.plist file, or config.xml file.
```

Likely related to #85 and #86

**Comment by utilityboy** [comment]
Closing in favour of #85
